name: Publishing

on: push

jobs:
  convert_via_pandoc:
    name: Convert via Pandoc
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: docker://pandoc/core:2.9
        with:
          args: "--standalone --output=public/index.html --css=css/bootstrap.min.css README.md"
      - name: Deploy Website
        if: github.ref == 'refs/heads/master'
        uses: maxheld83/rsync@v0.1.1
        with:
          args: $GITHUB_WORKSPACE/public/ pfs400wm@karli.rrze.uni-erlangen.de:/proj/websource/docs/FAU/fakultaet/phil/www.datascience.phil.fau.de/websource/printer
        env:
          HOST_NAME: karli.rrze.uni-erlangen.de
          HOST_IP: 131.188.16.138
          HOST_FINGERPRINT: ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBFHJVSekYKuF5pMKyHe1jS9mUkXMWoqNQe0TTs2sY1OQj379e6eqVSqGZe+9dKWzL5MRFpIiySRKgvxuHhaPQU4=
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
